# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c09b63b46b54ccbb2bf5596098a059a020034dc8ff86ec1f29a4a882e1ab7d6dd4c77653ac095b4b68e5494598b609d85f2be8ead3696c0c6150c26580c9325b

test:
  secret_key_base: d5e12eac445d82362076ab201db5ffacb5163dc7f8d9ed1c6bfdf36896ee55d50348badeb0c710677bcea78fac1fe25baa51e380e3c9bec744e7a3362591aeb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
